site_name: ethpwn - the Swiss Army Knife for Ethereum
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - tables
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - 🏠 Home: index.md
  - ⚔️ ethlib:
    - Usage: ethlib/usage.md
    - Global State: ethlib/global_state.md
    - Modules:
      - ethpwn.ethlib.global_context: ethlib/modules/global_context.md
      - ethpwn.ethlib.contract_registry: ethlib/modules/contract_registry.md
      - ethpwn.ethlib.contract_metadata: ethlib/modules/contract_metadata.md
      - ethpwn.ethlib.transactions: ethlib/modules/transactions.md
      - ethpwn.ethlib.hashes: ethlib/modules/hashes.md
      - ethpwn.ethlib.assembly_utils: ethlib/modules/assembly_utils.md
      - ethpwn.ethlib.currency_utils: ethlib/modules/currency_utils.md
      - ethpwn.ethlib.cli: ethlib/modules/cli.md
      - ethpwn.ethlib.compilation: ethlib/modules/compilation.md
      - ethpwn.ethlib.config: ethlib/modules/config.md
      - ethpwn.ethlib.prelude: ethlib/modules/prelude.md
      - ethpwn.ethlib.serialization_utils: ethlib/modules/serialization_utils.md
      - ethpwn.ethlib.utils: ethlib/modules/utils.md
    - CLI: ethlib/cli.md
    - Showroom: ethlib/showroom.md
  - 🐛 ethdbg:
    - Usage: ethdbg/usage.md
    - Commands:
      - start: ethdbg/commands/start.md
      - continue: ethdbg/commands/continue.md
      - context: ethdbg/commands/context.md
      - break: ethdbg/commands/break.md
      - tbreak: ethdbg/commands/tbreak.md
      - step: ethdbg/commands/step.md
      - next: ethdbg/commands/next.md
      - finish: ethdbg/commands/finish.md
      - log_op: ethdbg/commands/log_op.md
      - memory: ethdbg/commands/memory.md
      - sloads: ethdbg/commands/sloads.md
      - sstores: ethdbg/commands/sstores.md
      - storageat: ethdbg/commands/storageat.md
      - storagelayout: ethdbg/commands/storagelayout.md
      - callhistory: ethdbg/commands/callhistory.md
      - ethtowei: ethdbg/commands/ethtowei.md
      - weitoeth: ethdbg/commands/weitoeth.md
    - Showroom: ethdbg/showroom.md
  #- ⚙️ hacking ethdbg: hacking.md
  - ⛓️ chains support: chains.md
  - ？ FAQ: faq.md

